var res = {
	END_SCREEN_png: "res/END_SCREEN.png",
	TileGameResources_meta_tiles_png: "res/TileGameResources/meta_tiles.png",
	talha_png: "res/talha.png",
	progressbar_done_png: "res/progressbar_done.png",
	SpriteSheets_water_spritesheet_png: "res/SpriteSheets/water_spritesheet.png",
	target50x50_png: "res/target50x50.png",
	progressbar_left_png: "res/progressbar_left.png",
	demoSprite_jpg: "res/demoSprite.jpg",
	warnings_outside_png: "res/warnings/outside.png",
	demoSprite_png: "res/demoSprite.png",
	warnings_vert_png: "res/warnings/vert.png",
	Textbox_png: "res/Textbox.png",
	progressbar_thumb_png: "res/progressbar_thumb.png",
	StartScreen_omania_title_png: "res/StartScreen/omania_title.png",
	target34x34_png: "res/target34x34.png",
	Textbox_400width_png: "res/Textbox_400width.png",
	water_placeholder_png: "res/water_placeholder.png",
	TileSets_castle_architecture_png: "res/TileSets/castle_architecture.png",
	background_sand_png: "res/background/sand.png",
	StartScreen_Oman_title_start_png: "res/StartScreen/Oman_title_start.png",
	background_beach_png: "res/background/beach.png",
	StartScreen_start_bckgrnd_png: "res/StartScreen/start_bckgrnd.png",
	warnings_horiz_png: "res/warnings/horiz.png",
	wave_png: "res/wave.png",
	boulder_png: "res/boulder.png",
	building_png: "res/building.png",
	SpriteSheets_spritesheet_soldiers_png: "res/SpriteSheets/spritesheet_soldiers.png",
	background_sand_scroll_png: "res/background/sand_scroll.png",
	floor_png: "res/floor.png",
	warnings_inside_png: "res/warnings/inside.png",
	HelloWorld_png: "res/HelloWorld.png",
	TileGameResources_Player_png: "res/TileGameResources/Player.png",
	thirds_png: "res/thirds.png",
	castle_textbox_png: "res/castle_textbox.png",
	SpriteSheets_risingbuilding_spritesheet_png: "res/SpriteSheets/risingbuilding_spritesheet.png",
	arrows_png: "res/arrows.png",
	TileGameResources_TileMap_tmx: "res/TileGameResources/TileMap.tmx",
	aazaad_png: "res/aazaad.png",
	TileGameResources_tmw_desert_spacing_png: "res/TileGameResources/tmw_desert_spacing.png"
};

var g_resources = [];
for (var i in res) {
	g_resources.push(res[i]);
}
